### ISSUE TITLE
Unable to instantiate DragEvent in MicrosoftEdge

### ISSUE THREAD

**Issue by jonnycornwell** [kentcdodds/dom-testing-library#197]
- `dom-testing-library` version: 3.15.0
- `react` version: n/a
- `node` version: n/a
- `browser`: Microsoft Edge 42.17134.1.0 (Microsoft EdgeHTML 17.17134)
- `npm` (or `yarn`) version: n/a

### Relevant code or config:

```js
fireEvent.dragStart(element);
```

### What you did:

Used fireEvent to trigger a dragStart within Edge. We run our tests in the browser itself via intern.

### What happened:

JS runtime error: `SCRIPT5002: Function expected` 

### Reproduction:

Under the hood fireEvent is ultimately executing:
```
const EventConstructor = window['DragEvent']
const event = new EventConstructor('dragstart', {}) // Throws the error
```

### Problem description:

Cannot simulate drag events in Edge, the underlying issue is already logged in Edge https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14156632/. It will also most likely be resolved when Edge move to use Chromium

### Suggested solution:

I am not sure on the browser support for this library but a workaround could be added temporarily for this, I wanted to get feedback before creating a PR. It feels a bit horrible as it is using a deprecated API (`createEvent`) and you have to specify all params in order but ultimately it is for backwards compatibility. FireEvent could be updated to do something along these lines:

```
    const window = node.ownerDocument.defaultView
    const EventConstructor = window[EventType] || window.Event
    let event
    try {
      event = new EventConstructor(eventName, eventInit)
    } catch (error) {
      // Workaround for MicrosoftEdge as a DragEvent cannot be instantiated, https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14156632/
      if (EventType === 'DragEvent') {
        event = document.createEvent('DragEvent')
        event.initDragEvent(
          eventName,
          eventInit.bubbles,
          eventInit.cancelable,
          eventInit.view,
          eventInit.detail,
          eventInit.screenX,
          eventInit.screenY,
          eventInit.clientX,
          eventInit.clientY,
          eventInit.ctrlKey,
          eventInit.altKey,
          eventInit.shiftKey,
          eventInit.metaKey,
          eventInit.button,
          eventInit.relatedTarget,
          eventInit.dataTransfer,
        )
      } else {
        throw error
      }
    }

    return fireEvent(node, event)
```
I have held off doing a PR for now due to the nature of the changes and the resulting code which is not ideal. I am happy to make a PR with these changes if requested.

**Comment by kentcdodds** [comment]
Hi @jonnycornwell!

Thanks for filing this issue. Here's what I'm considering:

1. This is a bug in a platform that will hopefully eventually be fixed.
2. This is only happening on one platform.
3. 99.999% of dom-testing-library users are not running tests on that platform.
4. 99.999% of `fireEvent` calls are not for drag events.
5. There's a workaround which you can easily do in your own code.

So what we're left with is probably just one or two people running into this temporary problem for which there's a workaround. I don't think that's enough to justify adding code/tests to the codebase. So thank you for reporting it (maybe it'll help some poor soul coming from Google between now and when the bug is fixed), but I don't think we need to add this.

Thanks anyway and good luck!

**Comment by jonnycornwell** [comment]
@kentcdodds, thanks for getting back, that is the way I was leaning for sure, I just felt it would be worth raising for your thoughts and/or at least get an issue logged for future reference.
