### ISSUE TITLE
Provide chai assertions

### ISSUE THREAD

**Issue by pYr0x** [kentcdodds/dom-testing-library#7]
Would be nice to have chai assertions within this library

**Comment by kentcdodds** [comment]
Thanks for the contribution @pYr0x. I think I'd rather just add a link in the README to https://github.com/nathanboktae/chai-dom :+1:

**Comment by kentcdodds** [comment]
Would you be willing to add that?

**Comment by manishsaraan** [comment]
I would like to add this in readme

**Comment by kentcdodds** [comment]
Yes, I've been considering this. I think it would be a good idea 👍

**Comment by kentcdodds** [comment]
Thanks for doing that! As soon as you've got that published, then please feel free to open a PR to this repo to have it use that instead (probably only need to update `./extend-expect.js` to be `require('jest-dom/extend-expect')` or something, and remove all the other files associated to these extensions).

On the mono-repo idea. I'm sure it'd be great. Here are some of the problems I have with that approach:

1. I'm unfamiliar with how to make it work with automatic releases like I have right now. I don't have time to do manual releases.
2. It would significantly increase the noise I get in my notifications for things that I will never respond to (like for `vue` and friends).

So for now I don't have time to investigate how to overcome these problems I'm afraid :-/

**Comment by gnapse** [comment]
Yes sure, I wasn't even sure my self how would it work. In any case I think the org was a better idea than the mono repo, but probably also not really needed.

Will proceed with publishing the other repo. Do you mind giving a quick intro about that "automatic releases" thing you mentioned? If I used kcd-scripts in jest-dom, is there anything to be aware of about publishing it now and when it is updated in the future?

**Comment by kentcdodds** [comment]
In your project (clean, git-wise), run:

```
npx semantic-release-cli setup
```

Follow the prompts (use "Travis"). It'll make changes to your project, go ahead and `git reset --hard HEAD` with those because you don't need them. Make sure that your version is set to `0.0.0-semantically-released`, then push. It should kick in and start auto-releasing! Check out the `other/MAINTAINING.md` and `other/manual-releases.md` files to learn more about how that all works.

You can also watch this (a bit dated) video that includes the process (without kcd-scripts): http://kcd.im/write-oss
